/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import Business.ItemCatalogue.Items;
import Business.ItemCatalogue.ItemsDirectory;
import Business.Network.Network;
import Business.Orders.Orders;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sakshi
 * @author netra
 */
public class ClothingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClothingJPanel
     */
     private JPanel userProcessContainer;
      private Enterprise enterprise;
        private EcoSystem ecosystem;
        private Customer customer;
        private Items items;
        private ItemsDirectory itemsDirectory;
        private ArrayList<Items> orderItems = new ArrayList<Items>();
        private Orders order;
        private ArrayList<Orders> orderplaced = new ArrayList<Orders>();
        
	public ClothingJPanel(JPanel userProcessContainer, EcoSystem ecosystem, Customer customer, Enterprise enterprise ) {
            initComponents();
            this.userProcessContainer = userProcessContainer;
            this.ecosystem = ecosystem;
            this.customer = customer;
            populateTable();
             populatecart();
	}
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        clothingjComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        clothingJTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        transportsearch = new javax.swing.JTextField();
        btnAddtoCart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblclothingCart = new javax.swing.JTable();
        btnOrder = new javax.swing.JButton();
        tfTotalPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnDeleteCart = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        searchJTable = new javax.swing.JTable();
        searchcombobtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\__MACOSX\\New folder\\Price_Comparison_Businesses_System\\db4odemo\\images icons\\models.jpg")); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 30, 280, 660));

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jLabel1.setText("Services :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 70, 19));

        clothingjComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buy Fabric", "Readymade cloths", "Tailor services" }));
        clothingjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothingjComboBox1ActionPerformed(evt);
            }
        });
        clothingjComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clothingjComboBox1KeyPressed(evt);
            }
        });
        add(clothingjComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 160, -1));

        clothingJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                " Item name", "Description", "Price", "services F/R/T", "State", "Vendor name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(clothingJTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 796, 110));

        jLabel2.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jLabel2.setText("Search :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        add(transportsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 160, -1));

        btnAddtoCart.setText("Add to cart ");
        btnAddtoCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtoCartActionPerformed(evt);
            }
        });
        add(btnAddtoCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, -1));

        tblclothingCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                " Item name", "Description", "Price", "services F/R/T", "State", "Vendor name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblclothingCart);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 796, 120));

        btnOrder.setText("Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 630, -1, -1));
        add(tfTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 630, 72, -1));

        jLabel6.setText("Total Amount");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 630, -1, -1));

        btnDeleteCart.setText("Delete from cart");
        btnDeleteCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCartActionPerformed(evt);
            }
        });
        add(btnDeleteCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 630, -1, -1));

        searchJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                " Item name", "Description", "Price", "services F/R/T", "State", "Vendor name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(searchJTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 796, 130));

        searchcombobtn.setText("Search");
        searchcombobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchcombobtnActionPerformed(evt);
            }
        });
        add(searchcombobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/CustomerRole/1clothing.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, 140));

        jLabel5.setBackground(new java.awt.Color(167, 199, 231));
        jLabel5.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabel5.setText("Your Cart");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //            CustomerWorkAreaJPanel custAreajp = (CustomerWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void clothingjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothingjComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clothingjComboBox1ActionPerformed

    private void clothingjComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clothingjComboBox1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_clothingjComboBox1KeyPressed

    private void btnAddtoCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtoCartActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = searchJTable.getSelectedRow();

        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row!");
            return;
        }

        Items item =itemsDirectory.getItem(searchJTable.getValueAt(selectedRowIndex, 0).toString());
        orderItems.add(item);
        JOptionPane.showMessageDialog(tblclothingCart, "Item Added to cart");
        populatecart();

        //        else {
            //            // Dishes item=(Dishes)menuTable.getValueAt(selectedRow, 0);
            //
            //            Items cartitems =(Items)clothingJTable1.getValueAt(2, 0);
            //            populatecart(cartitems);
            //        }

    }//GEN-LAST:event_btnAddtoCartActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        int total = 0;
        System.out.println("WWW"+enterprise.getEnterpriseType());

        for(Items i : orderItems){
            total = total + parseInt(i.getItemprice());
        }

        order = new Orders(enterprise.getEnterpriseType().toString(), customer.getcustomerName(), orderItems, total, customer.getcustomerStreetAddress(), enterprise.getOrgAddress());

        orderplaced.add(order);

        if(customer.getOrderslist() != null){
            customer.getOrderslist().add(order);
            ArrayList<Orders> arr=enterprise.getOrders();
            arr.add(order);
            enterprise.setOrders(arr);//set the list
            JOptionPane.showMessageDialog(tblclothingCart, "Order Confirmed");
        }
        else{
            customer.newOrderslist();
            customer.getOrderslist().add(order);
            JOptionPane.showMessageDialog(tblclothingCart, "Order Confirmed");
        }
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnDeleteCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCartActionPerformed
        int selectedCartRow = tblclothingCart.getSelectedRow();
        if(selectedCartRow<0){
            JOptionPane.showMessageDialog(null,"Select a row","Warning",JOptionPane.WARNING_MESSAGE);
        }
        Items item = itemsDirectory.getItem(clothingJTable1.getValueAt(selectedCartRow, 0).toString());
        orderItems.remove(item);
        JOptionPane.showMessageDialog(tblclothingCart, "Item Deleted");
        populatecart();        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteCartActionPerformed

    private void searchcombobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchcombobtnActionPerformed
        // TODO add your handling code here:
              clothingjComboBox1.getSelectedItem();
    System.out.println(clothingjComboBox1.getSelectedItem());
    DefaultTableModel model = (DefaultTableModel) searchJTable.getModel();
        model.setRowCount(0);
        for(int i=0;i<itemsDirectory.getItemsList().size();i++)
        {
            System.out.println("line 153");
           
            if(itemsDirectory.getItemsList().get(i).getItemname().equals(transportsearch.getText()) && itemsDirectory.getItemsList().get(i).getItemservices().equals(clothingjComboBox1.getSelectedItem()) ){
                System.out.println("taru ki line ");
                System.out.println("line156 "+ itemsDirectory.getItemsList().get(i).getItemname());
                Object[] object={itemsDirectory.getItemsList().get(i).getItemname(),itemsDirectory.getItemsList().get(i).getItemdesc(),
                    itemsDirectory.getItemsList().get(i).getItemprice(),itemsDirectory.getItemsList().get(i).getItemservices(),
                    itemsDirectory.getItemsList().get(i).getItemstate()
                ,itemsDirectory.getItemsList().get(i).getItemsellertailorname(),itemsDirectory.getItemsList().get(i).getItemquantity()};
                model.addRow(object);
            
        }
     }
    }//GEN-LAST:event_searchcombobtnActionPerformed
 private void searchcomboActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        clothingjComboBox1.getSelectedItem();
    System.out.println(clothingjComboBox1.getSelectedItem());
    DefaultTableModel model = (DefaultTableModel) searchJTable.getModel();
        model.setRowCount(0);
        for(int i=0;i<itemsDirectory.getItemsList().size();i++)
        {
            System.out.println("line 153");
           
            if(itemsDirectory.getItemsList().get(i).getItemname().equals(transportsearch.getText()) && itemsDirectory.getItemsList().get(i).getItemservices().equals(clothingjComboBox1.getSelectedItem()) ){
                System.out.println("taru ki line ");
                System.out.println("line156 "+ itemsDirectory.getItemsList().get(i).getItemname());
                Object[] object={itemsDirectory.getItemsList().get(i).getItemname(),itemsDirectory.getItemsList().get(i).getItemdesc(),
                    itemsDirectory.getItemsList().get(i).getItemprice(),itemsDirectory.getItemsList().get(i).getItemservices(),
                    itemsDirectory.getItemsList().get(i).getItemstate()
                ,itemsDirectory.getItemsList().get(i).getItemsellertailorname(),itemsDirectory.getItemsList().get(i).getItemquantity()};
                model.addRow(object);
            
        }
     }
    }
//	  private void clothingjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                                   
//        // TODO add your handling code here:
//    }
//	 private void clothingjComboBox1KeyPressed(java.awt.event.KeyEvent evt) {                                              
//        // TODO add your handling code here:
//    }
//private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        // TODO add your handling code here:
//         int total = 0;
//         System.out.println("WWW"+enterprise.getEnterpriseType());
//        
//           
//            for(Items i : orderItems){
//                total = total + parseInt(i.getItemprice());
//            }
//
//           order = new Orders(enterprise.getEnterpriseType().toString(), customer.getcustomerName(), orderItems, total, customer.getcustomerStreetAddress(), enterprise.getOrgAddress());
//          
//            orderplaced.add(order);
//            
//            if(customer.getOrderslist() != null){
//                customer.getOrderslist().add(order);
//                ArrayList<Orders> arr=enterprise.getOrders();
//                arr.add(order);
//                enterprise.setOrders(arr);//set the list
//		JOptionPane.showMessageDialog(tblclothingCart, "Order Confirmed");
//            }
//            else{
//                customer.newOrderslist();
//                customer.getOrderslist().add(order);
//		JOptionPane.showMessageDialog(tblclothingCart, "Order Confirmed");
//            }
//    }
	
//	private void btnDeleteCartActionPerformed(java.awt.event.ActionEvent evt) {                                              
//          int selectedCartRow = tblclothingCart.getSelectedRow();
//            if(selectedCartRow<0){
//                JOptionPane.showMessageDialog(null,"Select a row","Warning",JOptionPane.WARNING_MESSAGE);
//            }
//            Items item = itemsDirectory.getItem(clothingJTable1.getValueAt(selectedCartRow, 0).toString());
//            orderItems.remove(item);
//	    JOptionPane.showMessageDialog(tblclothingCart, "Item Deleted");
//            populatecart();        // TODO add your handling code here:
//    }
//    private void btnAddtoCartActionPerformed(java.awt.event.ActionEvent evt) {                                             
//        // TODO add your handling code here:
//        int selectedRowIndex = clothingJTable1.getSelectedRow();
//        
//        if (selectedRowIndex<0){
//        JOptionPane.showMessageDialog(this, "Please select a row!");
//        return;
//    }
//        
//        Items item =itemsDirectory.getItem(clothingJTable1.getValueAt(selectedRowIndex, 0).toString());
//           orderItems.add(item);
//	    JOptionPane.showMessageDialog(tblclothingCart, "Item Added to cart");
//            populatecart();
//            
//            
////        else {
////            // Dishes item=(Dishes)menuTable.getValueAt(selectedRow, 0);
////            
////            Items cartitems =(Items)clothingJTable1.getValueAt(2, 0); 
////            populatecart(cartitems);
////        }
//        
//        
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddtoCart;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteCart;
    private javax.swing.JButton btnOrder;
    private javax.swing.JTable clothingJTable1;
    private javax.swing.JComboBox<String> clothingjComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable searchJTable;
    private javax.swing.JButton searchcombobtn;
    private javax.swing.JTable tblclothingCart;
    private javax.swing.JTextField tfTotalPrice;
    private javax.swing.JTextField transportsearch;
    // End of variables declaration//GEN-END:variables
private void populateTable() {
          for(Network n: ecosystem.getNetworkList()){
           for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
             if(e.getEnterpriseType().toString().equals("Clothing")){
               
               
                      itemsDirectory=e.getItemsDirectory(); 
                        enterprise=e;
              }
             
           }
          
          }
      DefaultTableModel model = (DefaultTableModel) clothingJTable1.getModel();
        model.setRowCount(0);
        
        System.out.println(itemsDirectory.getItemsList());
        for(Items i : itemsDirectory.getItemsList()){
            
            Object[] row = new Object[7];
            row[0] = i.getItemname();
            row[1] = i.getItemdesc();
            row[2] = i.getItemprice();
            row[3] = i.getItemservices();
            row[4] = i.getItemstate();
            row[5] = i.getItemsellertailorname();
            row[6] = i.getItemquantity();
            
            model.addRow(row);
            
        }
    }

    private void populatecart() {
    
        int total = 0;
            for(Items i : orderItems){
                total = total + parseInt(i.getItemprice());
            }
            tfTotalPrice.setText(String.valueOf(total));
        DefaultTableModel model = (DefaultTableModel) tblclothingCart.getModel();
        model.setRowCount(0);
        for(Items i : orderItems){
            Object[] row = new Object[7];
            row[0] = i.getItemname();
            row[1] = i.getItemdesc();
            row[2] = i.getItemprice();
            row[3] = i.getItemservices();
            row[4] = i.getItemstate();
            row[5] = i.getItemsellertailorname();
            row[6] = i.getItemquantity();
            
            model.addRow(row);
        }

    }
}
