

package userinterface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author  netra
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        valueLabel.setText(enterprise.getOrgName());
        if(enterprise.getEnterpriseType().getValue().equalsIgnoreCase("Service")){
            btnMenu.setText("Manage Services");
            btnManageOrders.setText("Manage Requests");
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnOrgAdmin = new javax.swing.JButton();
        btnNanageOrganization = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        btnManageOrders = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        jLabel1.setText("Welcome ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        btnOrgAdmin.setBackground(new java.awt.Color(167, 199, 231));
        btnOrgAdmin.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        btnOrgAdmin.setText("Manage Org Admin");
        btnOrgAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrgAdminActionPerformed(evt);
            }
        });
        add(btnOrgAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 220, -1));

        btnNanageOrganization.setBackground(new java.awt.Color(167, 199, 231));
        btnNanageOrganization.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        btnNanageOrganization.setText("Manage Organization");
        btnNanageOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNanageOrganizationActionPerformed(evt);
            }
        });
        add(btnNanageOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 220, -1));

        valueLabel.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 400, -1));

        btnManageOrders.setBackground(new java.awt.Color(167, 199, 231));
        btnManageOrders.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        btnManageOrders.setText("Manage Orders");
        btnManageOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrdersActionPerformed(evt);
            }
        });
        add(btnManageOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 220, -1));

        btnMenu.setBackground(new java.awt.Color(167, 199, 231));
        btnMenu.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        btnMenu.setText("Manage Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 220, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/icons/ent101.jpeg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 840, 660));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 600, 1270, 60));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/icons/order1.jpeg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 740, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrgAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrgAdminActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOrgAdminActionPerformed

    private void btnNanageOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNanageOrganizationActionPerformed

        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory(), enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnNanageOrganizationActionPerformed

        private void btnManageOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrdersActionPerformed
            // TODO add your handling code here:
            if(enterprise.getEnterpriseType().getValue().equalsIgnoreCase("Service")){
//                ManageRequests manageRequests = new ManageRequests(userProcessContainer, enterprise);
//                userProcessContainer.add("manageRequests", manageRequests);
//                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//                layout.next(userProcessContainer);
            }
            else{
                if(enterprise.getOrders() == null){
                    JOptionPane.showMessageDialog(null,"No Orders","Warning",JOptionPane.WARNING_MESSAGE);
                }
                else{
                    ManageOrdersJPanel manageOrdersJPanel = new ManageOrdersJPanel(userProcessContainer, enterprise);
                    userProcessContainer.add("manageOrdersJPanel", manageOrdersJPanel);
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                }
            }
        }//GEN-LAST:event_btnManageOrdersActionPerformed

        private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
            // TODO add your handling code here:
            
            if(enterprise.getEnterpriseType().getValue().equalsIgnoreCase("Service")){
                ManageServices manageServices = new ManageServices(userProcessContainer, enterprise);
                userProcessContainer.add("manageServices", manageServices);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            else{
                ManageMenuJPanel managemenuJPanel = new ManageMenuJPanel(userProcessContainer, enterprise);
                userProcessContainer.add("managemenuJPanel", managemenuJPanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
        }//GEN-LAST:event_btnMenuActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageOrders;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnNanageOrganization;
    private javax.swing.JButton btnOrgAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
