/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Customer.CustomerDirectory;
import Business.Enterprise.Enterprise;
import Business.ItemCatalogue.Items;
import Business.Orders.Orders;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author netra
 */
public class ViewOrdersJPanel extends javax.swing.JPanel {

	/**
	 * Creates new form ViewOrdersJPanel
	 */
	private Enterprise enterprise;;
        private JPanel userProcessContainer;
        private CustomerDirectory customerdir;
        private OrganizationDirectory orgdir;
        private Orders order;
	public ViewOrdersJPanel(JPanel userProcessContainer, Enterprise enterprise, Orders order) {
            initComponents();
            this.userProcessContainer = userProcessContainer;
            this.enterprise = enterprise;
            this.customerdir = enterprise.getCustomerdirectory();
            this.orgdir = enterprise.getOrganizationDirectory();
            this.order = order;
            tfOrderId.setText(String.valueOf(order.getOrderID()));
            tfStatus.setText(order.getStatus());
            tfTotalPrice.setText(String.valueOf(order.getTotalprice()));
            tfCustomerName.setText(order.getCustomerName());
            tfCustomerAddress.setText(order.getCustomerAddress());
            tfDeliveryName.setText(order.getDeliveryManName());
            tfDeliveryPhone.setText(order.getDeliveryPhone());
            tfEnterpriseName.setText(order.getEnterpriseName());
            populateOrderTable();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfOrderId = new javax.swing.JTextField();
        tfCustomerName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfTotalPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfCustomerAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfEnterpriseName = new javax.swing.JTextField();
        tfDeliveryName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfStatus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfDeliveryPhone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderJTable = new javax.swing.JTable();
        btnback = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Order Details");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 1, 160, 28));

        jLabel3.setText("Order ID :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 61, 80, 24));

        tfOrderId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOrderIdActionPerformed(evt);
            }
        });
        add(tfOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 59, 89, -1));
        add(tfCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 103, 89, -1));

        jLabel4.setText("Customer Name :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 105, 116, 24));
        add(tfTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 191, 89, -1));

        jLabel5.setText("Amount");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 193, 80, 24));
        add(tfCustomerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 147, 89, -1));

        jLabel6.setText("Customer Address");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 149, -1, 24));

        tfEnterpriseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEnterpriseNameActionPerformed(evt);
            }
        });
        add(tfEnterpriseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 61, 89, -1));
        add(tfDeliveryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 105, 89, -1));

        jLabel7.setText("Enterprise Name :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 63, 125, 24));

        jLabel8.setText("Delivery Man Name:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 107, -1, 24));

        tfStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStatusActionPerformed(evt);
            }
        });
        add(tfStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 193, 89, -1));

        jLabel9.setText("Status :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 194, 80, 24));
        add(tfDeliveryPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 149, 89, -1));

        jLabel10.setText("Delivery Man Contact :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 150, 127, 24));

        orderJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Description", "Price", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(orderJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 257, -1, 175));

        btnback.setText("<< Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tfOrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOrderIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfOrderIdActionPerformed

    private void tfEnterpriseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEnterpriseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEnterpriseNameActionPerformed

    private void tfStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStatusActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
userProcessContainer.remove(this);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.previous(userProcessContainer);                // TODO add your handling code here:userProcessContainer.remove(this);

               // TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderJTable;
    private javax.swing.JTextField tfCustomerAddress;
    private javax.swing.JTextField tfCustomerName;
    private javax.swing.JTextField tfDeliveryName;
    private javax.swing.JTextField tfDeliveryPhone;
    private javax.swing.JTextField tfEnterpriseName;
    private javax.swing.JTextField tfOrderId;
    private javax.swing.JTextField tfStatus;
    private javax.swing.JTextField tfTotalPrice;
    // End of variables declaration//GEN-END:variables

    private void populateOrderTable() {
        DefaultTableModel model = (DefaultTableModel) orderJTable.getModel();
        model.setRowCount(0);
        for(Items i : order.getOrderlist()){
            Object[] row = new Object[4]; 
            row[0] = i.getItemname();
            row[1] = i.getItemdesc();
            row[2] = i.getItemprice();
            row[3] = i.getItemquantity();
            
            model.addRow(row);
        }
    }
}
